### ISSUE TITLE
Hokusai setup in the docs

### ISSUE THREAD

**Issue by fclesio** [artsy/hokusai#248]
I was trying to configure Hokusai using the [docs](https://github.com/artsy/hokusai#setup) and I found out that the docs aren't complete. 

For example: In the docs says:
- 1) AWS Credentials,  
- 2) Run the `hokusai configure --kubectl-version <kubectl version> --s3-bucket <bucket name> --s3-key <file key>` command. 

However, running that command of the step 2, I got the following error:

![Screenshot from 2021-02-08 15-32-02](https://user-images.githubusercontent.com/10605378/107233922-640e7200-6a23-11eb-9c3d-835d5b04d470.png)

I think the `hokusai setup` should come before than the configure, no?

**Comment by dblandin** [comment]
@fclesio Thanks for the issue! I think that's actually a bug and not a documentation issue.

- `hokusai configure` is meant to configure hokusai dependencies globally like installing kubectl and pulling down kubernettes configuration files from S3.
- `hokusai setup` is for setting up a project to use hokusai

`hokusai setup` currently skips this check (because the project configuration files do not exist yet) but `hokusai configure` does not and I think that might be an oversight because I don't see anything in the command definition that relies on that project-specific context. Seems like you should be able to run `hokusai configure` anywhere on your system.

I've opened https://github.com/artsy/hokusai/pull/249 to enable the same `config_check=False` flag for the `configure` command.

**Comment by izakp** [comment]
Closed via #249
