### ISSUE TITLE
Hokusai push should parse .dockerignore file

### ISSUE THREAD

**Issue by izakp** [artsy/hokusai#57]
When running `hokusai push` it sanity checks a clean git checkout.  If `.gitignored` files are present, they should be checked against being present in the `.dockerignore` file

**Comment by artsyjian** [comment]
It seems this issue is mainly concerned with pushing from a developer's local, which is done for Review App creation, for example. It also seems the goal is to ensure Git-ignored files are not copied into the locally built Docker image, which can happen, if say a `.env` file is listed in `.gitignore` but not in `.dockerignore`, in other words, if the two Ignore files diverge. The solution would be to tell [Docker Compose build](https://github.com/artsy/hokusai/blob/d5f2cd3f5125c90041c5ea3a897d8e9245994200/hokusai/services/docker.py#L17) to exclude a list of files (and get the list from `git status --ignored`), but there's no way to do that.

The next best thing might be to warn user that a file is Git-ignored but not Docker-ignored, but there's no command to get a list of Docker-ignored files. Grep'ing `.dockerignore` file doesn't do.

It looks like the only thing Hokusai can do is just to print the list of Git-ignored files and warn user that if any of them is not Docker-ignored, it will be copied into the Docker image that `push` command will build, and if user is sure, re-run the command with `--force`. And what will the user do? Double check `.dockerignore`? Every time `push` is run? It does not seem practicable.

I think that ultimately the best thing is to ensure `.dockerignore` is in agreement with `.gitignore`, which does not seem to be Hokusai's responsibility at all.
